# Basic options
title: The Data Scientist
author: Mathias Modin
email: mathias.concha@gmail.com
description: "Powered by GitHub Pages, Jekyll and Indian food."
github_username: mmodin
url: https://mmodin.com

# Build settings
theme: minima
markdown: kramdown

# Stuff
permalink: /blog/:year-:month-:day/:title
google_analytics: UA-119114194-1

plugins:
    - jekyll-seo-tag

