# Basic options
title: The Data Scientist
author: Mathias Modin
email: mathias.concha@gmail.com
description: Useful stuffs
github_username: mmodin

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

# Site menu settings
menu:
  - title: "Blog"
    url: "/blog"
  - title: "Projects"
    url: "/projects"
